# Version '3.8' only will work with a least of docker-compose version 1.29.0
version: '3.8'
services:
        voting-app:
                image: voting-app-img:2.0
                container_name: app
                
                ports:
                        - "80:8080"
                
                restart: on-failure
