name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag image'
        required: true
        type: string
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    name: Building Docker Image
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  
    -
      if: ${{ inputs.tags }} 
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/votingweb:${{ inputs.tags }}
    -
      if: ${{ inputs.tags == '' }}
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/votingweb:latest
    
